// App
export const SET_DATA_FROM_API = "SET_DATA_FROM_API";
export const ADD_NOTE = "ADD_NOTE";
export const TOGGLE_TAB = "TOGGLE_TAB";
export const TOGGLE_HIDE_RIGHT_SIDEBAR = "TOGGLE_HIDE_RIGHT_SIDEBAR";
export const TOGGLE_HIDE_LEFT_SIDEBAR = "TOGGLE_HIDE_LEFT_SIDEBAR";
export const DELETE_TAG = "DELETE_TAG";
export const SET_ACTIVE_AREA_NOTE_ID = "SET_ACTIVE_AREA_NOTE_ID";
export const DELETE_NOTE = "DELETE_NOTE";
export const DELETE_NOTE_FOREVER = "DELETE_NOTE_FOREVER";
export const RESTORE_NOTE = "RESTORE_NOTE";
export const SAVE_NOTE = "SAVE_NOTE";
export const CLOSE_HIDE_LEFT_SIDEBAR = "CLOSE_HIDE_LEFT_SIDEBAR";
export const PIN_NOTE = "PIN_NOTE";
export const TOGGLE_TAGS_EDITABILITY = "TOGGLE_TAGS_EDITABILITY";
export const CHANGE_TAG_NAME = "CHANGE_TAG_NAME";
export const CHANGE_TAG_ORDER = "CHANGE_TAG_ORDER";
export const ADD_TAG = "SAVE_TAG";
export const SET_MAX_TAG_ORDER = "SET_MAX_TAG_ORDER";
export  const  REMOVE_TAG_FROM_NOTE = "REMOVE_TAG_FROM_NOTE";

// LeftSidebar
export const TOGGLE_LEFT_SIDEBAR = "TOGGLE_LEFT_SIDEBAR";
export const SEARCH_NOTES = "SEARCH_NOTES";
export const CLEAR_QUERY = "CLEAR_QUERY";
